time = 26.79151725769043
resolution_width = 87
resolution_height = 28
frequency = 10.0
amplitude = 1.0
speed = 0.5
color_shift = 0.0
scale = 1.0
octaves = 4
noise_strength = 0.15000000596046448
distort_amplitude = 0.5
noise_scale = 0.004999999888241291
z_rate = 0.019999999552965164
brightness = 1.2000000476837158
contrast = 1.0
hue = 0.0
saturation = 1.0
gamma = 1.0
vignette = 0.0
vignette_softness = 0.5
glyph_sharpness = 1.0
background_tint_r = 0.0
background_tint_g = 0.0
background_tint_b = 0.0
palette = "Braille"
color_mode = "Monochrome"
pattern_type = "Octgrams"
audio_enabled = false
bass_influence = 0.5
mid_influence = 0.30000001192092896
treble_influence = 0.20000000298023224
effect_time = -100.0
effect_type = 0
